# Generated by Django 2.2.9 on 2020-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200127_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text='Write here!', verbose_name='Description'),
        ),
    ]
